# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: flutter-analyze
        name: flutter-analyze
        language: system
        entry: bash -c "flutter analyze"
        verbose: true
    -   id: flutter-version
        name: flutter-version
        language: system
        entry: bash -c "flutter --version"
        verbose: true
    -   id: flutter-channel-list
        name: flutter-channel-list
        language: system
        entry: bash -c "flutter channel"
        verbose: true
    -   id: flutter-test
        name: flutter-test
        language: system
        entry: bash -c "flutter test"
        verbose: true
    -   id: flutter-version-2
        name: flutter-version-2
        language: system
        entry: bash -c "flutter --version"
        verbose: true
